languageCode = "en-US"
defaultContentLanguage = "en"

title = "EOS blockchain documentation"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[blackfriday]
  hrefTargetBlank = false

[params]
  editURL = "https://github.com/BinaryFocus/eosdocs.io/tree/master/PublicWebsite/content/"
  description = "EOSDocs.io - EOS developer documentation"
  author = "Warrick FitzGerald"
  showVisitedLinks = true
  disableLanguageSwitchingButton = true
  themeVariant = "mine"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "EOSDocs.io - EOS developer documentation"
weight = 1
languageName = "English"

